devpunks/snuggsi

- elements/parent-node.es
- examples/input-output.html
> Examples/input output.html

- examples/flashy.html
@brandondees can merge when satisfied. For now WIP.
> More examples:Flash.html

- elements/token-list.es
- examples/input-output.html
Fixes #44 
/cc @RobertChristopher @janz93
> Bound properties

- dist/snuggsi.es
- elements/component.es
- elements/event-target.es
- elements/global-event-handlers.es
- examples/infinity-calendar/index.html
- examples/infinity-calendar/infinity-calendar.es
- index.html
- snuggsi.js
> [Fixes #51] "Auto-Render" Exotic event handlers

- elements/component.es
> Named <template> <slot> replacement on HTMLLinkElement.import

- elements/token-list.es
Fixes #59 
[jsFiddle](https://t.co/9bmN97Sh2o)
> Fixes #59: Multiple {token}s within same TEXT_NODE

- examples/nav-view/example.html
- examples/nav-view/index.es
> 🐛BUGFIX - Fix `nav-router` load issue

- examples/x-flashy.html
> 🐛 BUGFIX gh-pages <x-flashy> page is busted

- dist/snuggsi.es
- elements/component.es
- elements/global-event-handlers.es
- examples/github-ribbon/example.html
> 83-slot-tokens-not-binding-to-class-after-import

- bin/publish
- elements/parent-node.es
- index.html
- sandbox.html
🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉 
🎉 🎉 🎉 🎉  🎉 🎉  🎉 🎉 🎉 🎉  #100 W00T 🎉 🎉 🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉 🎉 🎉 🎉
🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉  🎉 🎉
> 🎉 🎉  #100 🎉 🎉  Element.select `body ${a}` and  Element.selectAll `body ${b}` String Interpolation

- elements/html-template-element.es
- examples/infinity-calendar/index.html
- examples/infinity-calendar/infinity-calendar.es
> 🚀 🚀 🚀 🚀  <template name=value> render improvement!!!!

- .travis.yml
- README.md
- bin/crank
Just requested access to devpunks organization so I can add devpunks/snuggsi to travis-ci so I can test this. :-)
> basic travis-ci setup (#97)

- bin/shrink
🐛  Fixes #78
/cc @angelocordon
> 🐛 78 issue when shrinking

- README.md
> Fixes #140 update mission statement

- README.md
- examples/ie.html
Fixes #144 @brandondees @robcole @albertoponti @cristhiandick @kurtcagle 
Addresses #139 
Firefox now working. 🎉 #TOUCHDOWN 🏈 
Hello World @robcole - https://jsfiddle.net/snuggs/3zwkj9wg/
README updated.
> Issue Fix #144 firefox support not working

- .github/contributing.md
- .github/issue_template.md
- .github/pull_request_template.md
Add Templates to Snuggsi.
Resolving #146
[Link](https://github.com/blog/2111-issue-and-pull-request-templates)
> [Issue#146] Add PR and Issue Templates

- index.html
@snuggsi .. added the theme-color meta tag.
> added theme color meta tag

- package-lock.json
- package.json
Addresses:
- https://github.com/devpunks/snuggsi/issues/160
- https://github.com/devpunks/snuggsi/issues/161
> 🐞 [ BUGFIX] Broken `bin/cover` script.

- package-lock.json
- package.json
> 👊 Version Bump Dependencies

- .vscode/settings.json
- configure/README.md
- package.json
Closes #179 
Was a huge merge conflict in rianby64/master so created branch with commits from @rianby64's cloned master as a branch with no conflicts.
/cc @rianby64 @brandondees
> Improve the workspace

- .gitignore
- bin/integrate
Fixes #182 
Add blacklisted files to .gitignore (.npmignore)
> Fixes #182 shrink npm package size

- .github/FUNDING.yml
> Add Sponsorship button

- .vscode/README.md
- .vscode/settings.json
- README.md
1. Fixes bug in `.vscode/settings.json`
2. Adds `.test` extension to vscode
Test files have a `.test` extension but contain javascript _(for this project)_
@rianby64 can you quarterback this? ICANHAZ VIM. 🐱
/cc @brandondees
> Update vscode settings

- README.md
don't you hate it when strangers just stumble into your project just to fix a few typos in your doc?
> fix(README): typos
